### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by yexiaobai** [hjkl01/pornhub#35]
(venv) PS D:\workspace\pyws\pb\pornhub> python crawler.py mp4
2020-07-09 23:52:34.696 | INFO     | __main__:run:140 - url: https://www.pornhub.com/view_video.php?viewkey=ph564051ed6853e
D:\workspace\pyws\pb\pornhub\venv\lib\site-packages\urllib3\connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.pornhub.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
2020-07-09 23:52:40.282 | INFO     | __main__:detail_page:56 - JAV UNCENSORED
Traceback (most recent call last):
  File "crawler.py", line 157, in <module>
    fire.Fire(run)
  File "D:\workspace\pyws\pb\pornhub\venv\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\workspace\pyws\pb\pornhub\venv\lib\site-packages\fire\core.py", line 468, in _Fire
    target=component.__name__)
  File "D:\workspace\pyws\pb\pornhub\venv\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "crawler.py", line 141, in run
    detail_page(url)
  File "crawler.py", line 61, in detail_page
    file.write(js + '\n')
UnicodeEncodeError: 'gbk' codec can't encode character '\uac15' in position 8183: illegal multibyte sequence

**Comment by formateddd** [comment]
估计是视频名有中文字符，不然你考虑在linux下运行试试？
